import type { MatchRule } from './engine.js';
import { entropy, charClasses } from '../util.js';
import { jwtLooksValid } from './validators.js';
import {
  redactMiddle,
  redactUrlCreds,
  redactJwt,
  redactPrivateKey,
  redactFixed,
} from '../redact.js';

/**
 * Values that look like placeholders, not real secrets:
 * <YOUR_KEY>, ${VAR}, your_api_key_here, xxxx, changeme, env refs, etc.
 */
const PLACEHOLDER = new RegExp(
  '^(?:' +
    [
      'x{3,}',
      '\\*{3,}',
      '•+',
      '<[^>]*>?',
      '\\$\\{[^}]*\\}?',
      '\\$[A-Z_][A-Z0-9_]*',
      '%[a-z0-9_]+%',
      'your[a-z0-9_-]*',
      'my[a-z0-9_-]*',
      'sample[a-z0-9_-]*',
      'example[a-z0-9_-]*',
      'placeholder[a-z0-9_-]*',
      'change[_-]?me',
      'change[_-]?this',
      'dummy[a-z0-9_-]*',
      'test[a-z0-9_-]*',
      'fake[a-z0-9_-]*',
      'foo|bar|baz',
      'abc[0-9]*',
      '123[0-9]*',
      'password|passw0rd|secret|token|apikey|api[_-]?key|value|string',
      'none|null|undefined|true|false|empty|blank',
      'redacted|hidden|masked|omitted|removed|snip|censored',
      'todo|tbd|fixme',
      'insert[a-z0-9_-]*|replace[a-z0-9_-]*|put[a-z0-9_-]*|paste[a-z0-9_-]*|add[a-z0-9_-]*',
      'env\\..*|process\\.env.*|os\\.environ.*|getenv.*|config\\..*|settings\\..*|self\\..*|this\\..*',
    ].join('|') +
    ')$',
  'i',
);

/** SCREAMING_SNAKE env-var references like MY_API_KEY (case-sensitive on purpose). */
const ENV_VAR_REF = /^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+$/;

export function isPlaceholder(v: string): boolean {
  return PLACEHOLDER.test(v) || ENV_VAR_REF.test(v) || /\.{3}/.test(v) || /^(.)\1+$/.test(v);
}

/** Words that follow "password is/:" in prose but are never the password itself. */
const PASSWORD_STOPWORDS = new Set([
  'required', 'optional', 'invalid', 'incorrect', 'correct', 'wrong', 'expired',
  'hashed', 'encrypted', 'stored', 'hidden', 'masked', 'protected', 'disabled',
  'enabled', 'missing', 'empty', 'blank', 'unknown', 'forgotten', 'changed',
  'reset', 'strong', 'stronger', 'weak', 'secure', 'insecure', 'random',
  'string', 'field', 'prompt', 'manager', 'managers', 'policy',
  'always', 'never', 'usually', 'often', 'still', 'already', 'automatically',
  'different', 'identical', 'sensitive', 'visible', 'plaintext', 'case-sensitive',
]);

function plausibleGenericSecret(v: string): boolean {
  if (isPlaceholder(v)) return false;
  if (entropy(v) < 3.2) return false;
  if (charClasses(v) < 2) return false;
  return true;
}

function plausiblePassword(raw: string): boolean {
  const v = raw.replace(/^["'`(\[]+|["'`.,;:!?)\]]+$/g, '');
  if (v.length < 6 || v.length > 64) return false;
  if (isPlaceholder(v)) return false;
  if (PASSWORD_STOPWORDS.has(v.toLowerCase())) return false;
  if (/[()]/.test(v)) return false; // code refs like getPassword()
  if (/^[-*•=_#~^]+$/.test(v)) return false;
  if (/^[a-z]+$/.test(v) && v.length < 8) return false; // "password is secret" style prose
  return true;
}

const r = (pattern: string, flags = ''): RegExp => new RegExp(pattern, `gd${flags}`);

/**
 * Layer 1: secrets & credentials. High precision — every rule either has a
 * distinctive prefix, a checksum/structure validator, entropy gating, or
 * required context. Severity CRITICAL unless noted.
 */
export const SECRET_RULES: MatchRule[] = [
  {
    id: 'private-key-block',
    title: 'Private key block',
    severity: 'critical',
    layer: 1,
    pattern: r('-----BEGIN [A-Z ]*PRIVATE KEY(?: BLOCK)?-----[\\s\\S]{0,8000}?(?:-----END [A-Z ]*PRIVATE KEY(?: BLOCK)?-----|$)'),
    prefilter: ['private key'],
    priority: 100,
    redact: redactPrivateKey,
    normalize: (v) => v.replace(/\s+/g, '').slice(0, 256),
    remediation: 'Treat this key as compromised. Generate a new keypair and revoke this one everywhere it is authorized (servers, GitHub deploy keys, cloud consoles).',
  },
  {
    id: 'anthropic-api-key',
    title: 'Anthropic API key',
    severity: 'critical',
    layer: 1,
    pattern: r('\\bsk-ant-[A-Za-z0-9_-]{16,}\\b'),
    prefilter: ['sk-ant-'],
    priority: 95,
    redact: (v) => redactMiddle(v),
    remediation: 'Revoke and rotate at console.anthropic.com → Settings → API Keys.',
  },
  {
    id: 'openai-api-key',
    title: 'OpenAI API key',
    severity: 'critical',
    layer: 1,
    pattern: r('\\bsk-(?!ant-)[A-Za-z0-9_-]{20,}\\b'),
    prefilter: ['sk-'],
    validate: (v) => /\d/.test(v) && /[a-zA-Z]/.test(v) && entropy(v) >= 3,
    priority: 94,
    redact: (v) => redactMiddle(v),
    remediation: 'Revoke and rotate at platform.openai.com → API keys.',
  },
  {
    id: 'github-token',
    title: 'GitHub personal access token',
    severity: 'critical',
    layer: 1,
    pattern: r('\\b(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{36,255}\\b'),
    prefilter: ['ghp_', 'gho_', 'ghu_', 'ghs_', 'ghr_'],
    priority: 93,
    redact: (v) => redactMiddle(v),
    remediation: 'Revoke at github.com → Settings → Developer settings → Personal access tokens.',
  },
  {
    id: 'github-fine-grained-token',
    title: 'GitHub fine-grained token',
    severity: 'critical',
    layer: 1,
    pattern: r('\\bgithub_pat_[A-Za-z0-9_]{22,255}\\b'),
    prefilter: ['github_pat_'],
    priority: 93,
    redact: (v) => redactMiddle(v),
    remediation: 'Revoke at github.com → Settings → Developer settings → Fine-grained tokens.',
  },
  {
    id: 'gitlab-token',
    title: 'GitLab personal access token',
    severity: 'critical',
    layer: 1,
    pattern: r('\\bglpat-[A-Za-z0-9_-]{20,}\\b'),
    prefilter: ['glpat-'],
    priority: 93,
    redact: (v) => redactMiddle(v),
    remediation: 'Revoke at gitlab.com → Preferences → Access Tokens.',
  },
  {
    id: 'aws-access-key-id',
    title: 'AWS access key ID',
    severity: 'critical',
    layer: 1,
    pattern: r('\\b(?:AKIA|ASIA|ABIA|ACCA)[0-9A-Z]{16}\\b'),
    prefilter: ['akia', 'asia', 'abia', 'acca'],
    priority: 92,
    redact: (v) => redactMiddle(v),
    remediation: 'Deactivate the key at console.aws.amazon.com/iam → Users → Security credentials, then rotate.',
  },
  {
    id: 'aws-secret-access-key',
    title: 'AWS secret access key',
    severity: 'critical',
    layer: 1,
    pattern: r('(?<![A-Za-z0-9/+])([A-Za-z0-9/+]{40})(?![A-Za-z0-9/+=])'),
    group: 1,
    prefilter: ['aws'],
    context: /aws|amazon|secret[_ -]?access[_ -]?key|aws_secret/i,
    validate: (v) => entropy(v) >= 3.5 && /[A-Z]/.test(v) && /[a-z]/.test(v) && /\d|\//.test(v),
    priority: 70,
    redact: (v) => redactMiddle(v),
    remediation: 'Deactivate the key pair at console.aws.amazon.com/iam and rotate.',
  },
  {
    id: 'google-api-key',
    title: 'Google API key',
    severity: 'critical',
    layer: 1,
    pattern: r('\\bAIza[0-9A-Za-z_-]{35}\\b'),
    prefilter: ['aiza'],
    priority: 92,
    redact: (v) => redactMiddle(v),
    remediation: 'Regenerate at console.cloud.google.com → APIs & Services → Credentials.',
  },
  {
    id: 'gcp-service-account',
    title: 'GCP service account JSON',
    severity: 'critical',
    layer: 1,
    pattern: r('"type"\\s*:\\s*"service_account"'),
    prefilter: ['service_account'],
    priority: 90,
    normalize: () => 'service_account_json',
    redact: redactFixed('GCP SERVICE ACCOUNT JSON'),
    remediation: 'Delete this key at console.cloud.google.com → IAM & Admin → Service Accounts → Keys, and issue a new one.',
  },
  {
    id: 'azure-storage-key',
    title: 'Azure storage account key',
    severity: 'critical',
    layer: 1,
    pattern: r('AccountKey=([A-Za-z0-9+/]{86}==)'),
    group: 1,
    prefilter: ['accountkey='],
    priority: 92,
    redact: (v) => redactMiddle(v),
    remediation: 'Rotate the storage keys at portal.azure.com → Storage account → Access keys.',
  },
  {
    id: 'slack-token',
    title: 'Slack token',
    severity: 'critical',
    layer: 1,
    pattern: r('\\bxox[baprs]-[A-Za-z0-9-]{10,250}\\b'),
    prefilter: ['xox'],
    priority: 92,
    redact: (v) => redactMiddle(v),
    remediation: 'Revoke via api.slack.com → Your Apps → OAuth & Permissions (or rotate the bot token).',
  },
  {
    id: 'slack-webhook',
    title: 'Slack incoming webhook URL',
    severity: 'high',
    layer: 1,
    pattern: r('hooks\\.slack\\.com/services/T[A-Za-z0-9_/]{8,}'),
    prefilter: ['hooks.slack.com'],
    priority: 88,
    redact: (v) => 'hooks.slack.com/services/' + redactMiddle(v.split('/services/')[1] ?? '', 3),
    remediation: 'Remove and recreate the webhook in your Slack app settings.',
  },
  {
    id: 'stripe-live-key',
    title: 'Stripe live secret key',
    severity: 'critical',
    layer: 1,
    pattern: r('\\b[sr]k_live_[A-Za-z0-9]{16,}\\b'),
    prefilter: ['k_live_'],
    priority: 92,
    redact: (v) => redactMiddle(v),
    remediation: 'Roll the key immediately at dashboard.stripe.com → Developers → API keys.',
  },
  {
    id: 'stripe-test-key',
    title: 'Stripe test-mode key',
    severity: 'high',
    layer: 1,
    pattern: r('\\b[sr]k_test_[A-Za-z0-9]{16,}\\b'),
    prefilter: ['k_test_'],
    priority: 92,
    redact: (v) => redactMiddle(v),
    remediation: 'Roll at dashboard.stripe.com → Developers → API keys (test keys still allow test-mode writes).',
  },
  {
    id: 'sendgrid-api-key',
    title: 'SendGrid API key',
    severity: 'critical',
    layer: 1,
    pattern: r('\\bSG\\.[A-Za-z0-9_-]{16,32}\\.[A-Za-z0-9_-]{16,64}\\b'),
    prefilter: ['sg.'],
    priority: 92,
    redact: (v) => redactMiddle(v),
    remediation: 'Delete and recreate at app.sendgrid.com → Settings → API Keys.',
  },
  {
    id: 'npm-token',
    title: 'npm access token',
    severity: 'critical',
    layer: 1,
    pattern: r('\\bnpm_[A-Za-z0-9]{36}\\b'),
    prefilter: ['npm_'],
    priority: 92,
    redact: (v) => redactMiddle(v),
    remediation: 'Revoke at npmjs.com → Access Tokens.',
  },
  {
    id: 'huggingface-token',
    title: 'Hugging Face token',
    severity: 'critical',
    layer: 1,
    pattern: r('\\bhf_[A-Za-z0-9]{30,}\\b'),
    prefilter: ['hf_'],
    priority: 92,
    redact: (v) => redactMiddle(v),
    remediation: 'Invalidate at huggingface.co → Settings → Access Tokens.',
  },
  {
    id: 'digitalocean-token',
    title: 'DigitalOcean token',
    severity: 'critical',
    layer: 1,
    pattern: r('\\bdop_v1_[a-f0-9]{64}\\b'),
    prefilter: ['dop_v1_'],
    priority: 92,
    redact: (v) => redactMiddle(v),
    remediation: 'Revoke at cloud.digitalocean.com → API → Tokens.',
  },
  {
    id: 'shopify-token',
    title: 'Shopify access token',
    severity: 'critical',
    layer: 1,
    pattern: r('\\bshp(?:at|ca|pa|ss)_[a-fA-F0-9]{32}\\b'),
    prefilter: ['shpat_', 'shpca_', 'shppa_', 'shpss_'],
    priority: 92,
    redact: (v) => redactMiddle(v),
    remediation: 'Rotate in your Shopify admin → Apps → Develop apps.',
  },
  {
    id: 'pypi-token',
    title: 'PyPI API token',
    severity: 'critical',
    layer: 1,
    pattern: r('\\bpypi-AgEIcHlwaS5vcmc[A-Za-z0-9_-]{20,}\\b'),
    prefilter: ['pypi-'],
    priority: 92,
    redact: (v) => redactMiddle(v),
    remediation: 'Revoke at pypi.org → Account settings → API tokens.',
  },
  {
    id: 'twilio-api-key',
    title: 'Twilio API key',
    severity: 'critical',
    layer: 1,
    pattern: r('\\bSK[0-9a-f]{32}\\b'),
    prefilter: ['twilio'],
    context: /twilio/i,
    priority: 85,
    redact: (v) => redactMiddle(v),
    remediation: 'Revoke at console.twilio.com → Account → API keys & tokens.',
  },
  {
    id: 'telegram-bot-token',
    title: 'Telegram bot token',
    severity: 'critical',
    layer: 1,
    pattern: r('\\b\\d{8,10}:AA[A-Za-z0-9_-]{33}\\b'),
    prefilter: [':aa'],
    priority: 92,
    redact: (v) => redactMiddle(v),
    remediation: 'Revoke via @BotFather → /revoke.',
  },
  {
    id: 'discord-bot-token',
    title: 'Discord bot token',
    severity: 'critical',
    layer: 1,
    pattern: r('\\b[MN][A-Za-z0-9_-]{23,25}\\.[A-Za-z0-9_-]{6,7}\\.[A-Za-z0-9_-]{25,40}\\b'),
    prefilter: ['discord'],
    context: /discord|bot[ _-]?token/i,
    priority: 85,
    redact: (v) => redactMiddle(v),
    remediation: 'Regenerate at discord.com/developers → Your App → Bot → Reset Token.',
  },
  {
    id: 'db-connection-uri',
    title: 'Database URI with credentials',
    severity: 'critical',
    layer: 1,
    pattern: r("\\b(?:postgres(?:ql)?|mysql|mariadb|mongodb(?:\\+srv)?|redis|rediss|amqp|amqps|mssql|ftp|sftp)://[^\\s:@/'\"<>]{1,64}:[^\\s@/'\"<>]{1,128}@[^\\s'\"<>)\\]}]+"),
    prefilter: ['://'],
    priority: 86,
    redact: redactUrlCreds,
    remediation: 'Change the database password on the server, then update every connection string that used it.',
  },
  {
    id: 'url-basic-auth',
    title: 'URL with embedded credentials',
    severity: 'critical',
    layer: 1,
    pattern: r("\\bhttps?://[^\\s:@/'\"<>]{1,64}:[^\\s@/'\"<>]{3,128}@[^\\s'\"<>)\\]}]+"),
    prefilter: ['http'],
    priority: 84,
    redact: redactUrlCreds,
    remediation: 'Rotate the credential embedded in this URL and stop passing auth in URLs where possible.',
  },
  {
    id: 'jwt',
    title: 'JWT (bearer token)',
    severity: 'critical',
    layer: 1,
    pattern: r('\\beyJ[A-Za-z0-9_-]{8,}\\.[A-Za-z0-9_-]{8,}\\.[A-Za-z0-9_-]{8,}\\b'),
    prefilter: ['eyj'],
    validate: (v) => jwtLooksValid(v),
    priority: 80,
    redact: redactJwt,
    remediation: 'Invalidate the session it belongs to; if it is long-lived, rotate the signing secret.',
  },
  {
    id: 'bearer-token',
    title: 'Bearer token',
    severity: 'critical',
    layer: 1,
    pattern: r('\\bBearer\\s+([A-Za-z0-9_\\-.=+/]{20,})', 'i'),
    group: 1,
    prefilter: ['bearer'],
    validate: (v) => plausibleGenericSecret(v),
    priority: 60,
    redact: (v) => redactMiddle(v),
    remediation: 'Revoke the token with the issuing service.',
  },
  {
    id: 'generic-secret-assignment',
    title: 'API key / secret assignment',
    severity: 'critical',
    layer: 1,
    pattern: r(
      '\\b(api[_-]?key|apikey|api[_-]?secret|secret[_-]?key|client[_-]?secret|access[_-]?token|auth[_-]?token|refresh[_-]?token|encryption[_-]?key|signing[_-]?key|token|secret)\\b["\']?\\s*[:=]\\s*["\']?([A-Za-z0-9_\\-.+/=]{12,128})["\']?',
      'i',
    ),
    group: 2,
    prefilter: ['key', 'token', 'secret'],
    validate: (v) => plausibleGenericSecret(v),
    priority: 40,
    redact: (v) => redactMiddle(v),
    remediation: 'Rotate this credential with whatever service issued it.',
  },
  {
    id: 'password-assignment',
    title: 'Password',
    severity: 'critical',
    layer: 1,
    pattern: r('\\b(?:password|passwd|pwd|passphrase)\\b["\']?\\s*(?:[:=]|\\bis\\b)\\s*["\']?(\\S{6,64})', 'i'),
    group: 1,
    prefilter: ['pass', 'pwd'],
    validate: (v) => plausiblePassword(v),
    priority: 42,
    redact: (v) => redactMiddle(v, 2),
    remediation: 'Change this password everywhere it is used, and enable 2FA on the account.',
  },
];
